/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "worldborderapi"


pluginManagement {
    repositories {
        maven("https://papermc.io/repo/repository/maven-public/")
        gradlePluginPortal()
        maven("https://repo.jpenilla.xyz/snapshots/")
        maven("https://eldonexus.de/repository/maven-public/")
    }
}
