/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "WorldBorderAPI"
include("api")
include("version_1_16")
include("version_1_17")
include("plugin")
include("testplugin")
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")
