/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.yannicklamprecht.java-conventions")
}

dependencies {
    compileOnly(projects.api)
    compileOnly("org.spigotmc:spigot:1.14.4-R0.1-SNAPSHOT")
}

description = "version_1_14"

apply<WorldBorderApiToolsPlugin>()

val build14 = tasks.register<BuildSpigotTask>("buildSpigot"){
    version = "1.14.4"
}
