/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.yannicklamprecht.java-conventions")
}

dependencies {
    compileOnly(projects.api)
    compileOnly("org.spigotmc:spigot:1.15.2-R0.1-SNAPSHOT")
}

description = "version_1_15"

apply<WorldBorderApiToolsPlugin>()

val build15 =tasks.register<BuildSpigotTask>("buildSpigot"){
    version = "1.15.2"
}
