/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.yannicklamprecht.java-conventions")
}

dependencies {
    compileOnly(projects.api)
    compileOnly("org.spigotmc:spigot:1.17-R0.1-SNAPSHOT") // todo add classifier ":remapped-mojang" when special source is fixed or another tool is implemented
}

description = "version_1_17"
apply<WorldBorderApiToolsPlugin>()

tasks.register<BuildSpigotTask>("buildSpigot"){
    version.set("1.17")
    mojangMapped.set(false) // todo set to "true" when special source is fixed or another tool is implemented
}
