/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.yannicklamprecht.java-conventions")
}

dependencies {
    compileOnly(projects.api)
    compileOnly("org.spigotmc:spigot:1.17-R0.1-SNAPSHOT:remapped-mojang")
}

description = "version_1_17"

apply<SpigotTools>()

tasks {
    register<BuildSpigotTask>("buildSpigot") {
        version.set("1.17")
        mojangMapped.set(true)
    }
    register<RemapJar>("remapJar") {
        spigotVersion.set("1.17-R0.1-SNAPSHOT")
    }
}
