/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.yannicklamprecht.java-conventions")
    id("com.github.johnrengelman.shadow") version shadowVersion
}

dependencies {
    implementation(projects.api)
    implementation(projects.version116)
    compileOnly("org.spigotmc:spigot-api:1.14.4-R0.1-SNAPSHOT")
}

description = "plugin"
