/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.yannicklamprecht.java-conventions")
    id("com.github.johnrengelman.shadow") version "6.1.0"
}

dependencies {
    implementation(project(":API"))
    implementation(project(":1_14_R1"))
    implementation(project(":1_15_R1"))
    implementation(project(":1_16_R3"))
    compileOnly("org.spigotmc:spigot-api:1.14.4-R0.1-SNAPSHOT")
}

description = "WorldBorderPlugin"
