/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.yannicklamprecht.java-conventions")
}

dependencies {
    compileOnly(projects.api)
    compileOnly("org.spigotmc:spigot:1.16.5-R0.1-SNAPSHOT")
}

description = "version_1_16"
apply<SpigotTools>()

tasks.register("buildSpigot", BuildSpigotTask::class){
    version.set("1.16.5")
    mojangMapped.set(false)
}
