/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.yannicklamprecht.java-conventions")
    id("com.github.yannicklamprecht.spigot.tools") version "1.0.1"
}

dependencies {
    compileOnly(projects.api)
    compileOnly("org.spigotmc:spigot:1.16.5-R0.1-SNAPSHOT")
}

description = "version_1_16"

tasks {
    spigotTools {
        mojangMapped.set(false)
        version.set("1.16.5")
    }
}
