/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.yannicklamprecht.java-conventions")
}

dependencies {
    compileOnly(project(":API"))
    compileOnly("org.spigotmc:spigot:1.15.2-R0.1-SNAPSHOT")
}

description = "1_15_R1"

apply<WorldBorderApiToolsPlugin>()

val build15 =tasks.register<BuildSpigotTask>("buildSpigot"){
    version = "1.15.2"
}
